"""add_stars_payment_ids_to_users

Revision ID: 1c1e8885a654
Revises: 706e284f23f8
Create Date: 2025-09-10 03:50:06.590677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1e8885a654'
down_revision: Union[str, Sequence[str], None] = '706e284f23f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stars_payment_ids', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stars_payment_ids')
    # ### end Alembic commands ###