"""crash_update

Revision ID: 28854cdf8ef5
Revises: 11ec9b6ed324
Create Date: 2025-09-10 05:56:29.736226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28854cdf8ef5'
down_revision: Union[str, Sequence[str], None] = '11ec9b6ed324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('crash_game_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rtp', sa.Float(), nullable=True),
    sa.Column('house_edge', sa.Float(), nullable=True),
    sa.Column('min_multiplier', sa.Float(), nullable=True),
    sa.Column('max_multiplier', sa.Float(), nullable=True),
    sa.Column('crash_point_distribution', sa.String(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_game_settings_id'), 'crash_game_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crash_game_settings_id'), table_name='crash_game_settings')
    op.drop_table('crash_game_settings')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
