"""crash_update

Revision ID: 706e284f23f8
Revises: c52f7a177509
Create Date: 2025-09-05 01:20:08.251509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706e284f23f8'
down_revision: Union[str, Sequence[str], None] = 'c52f7a177509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('crashed_at', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=True),
    sa.Column('total_bet', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_payout', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crash_game_id', 'crash_game_results', ['game_id'], unique=False)
    op.create_index('idx_crash_timestamp', 'crash_game_results', ['timestamp'], unique=False)
    op.create_index(op.f('ix_crash_game_results_game_id'), 'crash_game_results', ['game_id'], unique=False)
    op.create_index(op.f('ix_crash_game_results_id'), 'crash_game_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crash_game_results_id'), table_name='crash_game_results')
    op.drop_index(op.f('ix_crash_game_results_game_id'), table_name='crash_game_results')
    op.drop_index('idx_crash_timestamp', table_name='crash_game_results')
    op.drop_index('idx_crash_game_id', table_name='crash_game_results')
    op.drop_table('crash_game_results')
    # ### end Alembic commands ###
