"""add_photo_url_to_users

Revision ID: c942584428af
Revises: 52d4cfabc133
Create Date: 2025-08-29 00:27:04.621541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c942584428af'
down_revision: Union[str, Sequence[str], None] = '52d4cfabc133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
